include: package:lint/analysis_options.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.gr.dart]

linter:
  rules:
    prefer_single_quotes: true
    always_specify_types: true
